"""initial_tables

Revision ID: 09d0389c0b53
Revises: 
Create Date: 2026-01-02 15:01:02.191805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d0389c0b53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create prop_line_snapshots table
    op.create_table(
        'prop_line_snapshots',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('event_id', sa.String(length=100), nullable=False),
        sa.Column('game_commence_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('home_team', sa.String(length=100), nullable=True),
        sa.Column('away_team', sa.String(length=100), nullable=True),
        sa.Column('player_name', sa.String(length=200), nullable=False),
        sa.Column('player_slug', sa.String(length=200), nullable=True),
        sa.Column('team', sa.String(length=100), nullable=True),
        sa.Column('prop_type', sa.Enum('RUSHING_YARDS', 'RECEIVING_YARDS', name='proptype'), nullable=False),
        sa.Column('consensus_line', sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column('draftkings_line', sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column('fanduel_line', sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column('betmgm_line', sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column('caesars_line', sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column('pointsbet_line', sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column('over_odds', sa.Integer(), nullable=True),
        sa.Column('under_odds', sa.Integer(), nullable=True),
        sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.Column('hours_before_kickoff', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('source', sa.Enum('BETTINGPROS', 'ODDS_API', name='datasource'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('raw_data', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prop_game_time', 'prop_line_snapshots', ['game_commence_time'], unique=False)
    op.create_index('idx_prop_snapshot_lookup', 'prop_line_snapshots', ['event_id', 'player_name', 'prop_type', 'snapshot_time'], unique=False)
    op.create_index('idx_prop_snapshot_time', 'prop_line_snapshots', ['snapshot_time'], unique=False)
    op.create_index(op.f('ix_prop_line_snapshots_event_id'), 'prop_line_snapshots', ['event_id'], unique=False)
    op.create_index(op.f('ix_prop_line_snapshots_player_name'), 'prop_line_snapshots', ['player_name'], unique=False)

    # Create player_game_stats table
    op.create_table(
        'player_game_stats',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('event_id', sa.String(length=100), nullable=False),
        sa.Column('game_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('season', sa.Integer(), nullable=False),
        sa.Column('week', sa.Integer(), nullable=False),
        sa.Column('player_name', sa.String(length=200), nullable=False),
        sa.Column('player_id', sa.String(length=50), nullable=True),
        sa.Column('team', sa.String(length=100), nullable=True),
        sa.Column('opponent', sa.String(length=100), nullable=True),
        sa.Column('rushing_attempts', sa.Integer(), nullable=True),
        sa.Column('rushing_yards', sa.Integer(), nullable=True),
        sa.Column('rushing_tds', sa.Integer(), nullable=True),
        sa.Column('receptions', sa.Integer(), nullable=True),
        sa.Column('receiving_targets', sa.Integer(), nullable=True),
        sa.Column('receiving_yards', sa.Integer(), nullable=True),
        sa.Column('receiving_tds', sa.Integer(), nullable=True),
        sa.Column('is_home', sa.Boolean(), nullable=True),
        sa.Column('game_result', sa.String(length=10), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_player_stats_event', 'player_game_stats', ['event_id'], unique=False)
    op.create_index('idx_player_stats_lookup', 'player_game_stats', ['player_name', 'game_date'], unique=False)
    op.create_index(op.f('ix_player_game_stats_event_id'), 'player_game_stats', ['event_id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_player_name'), 'player_game_stats', ['player_name'], unique=False)

    # Create line_movements table
    op.create_table(
        'line_movements',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('event_id', sa.String(length=100), nullable=False),
        sa.Column('player_name', sa.String(length=200), nullable=False),
        sa.Column('prop_type', sa.Enum('RUSHING_YARDS', 'RECEIVING_YARDS', name='proptype'), nullable=False),
        sa.Column('initial_line', sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column('final_line', sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column('initial_snapshot_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('final_snapshot_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('movement_absolute', sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column('movement_pct', sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column('hours_before_kickoff', sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column('actual_yards', sa.Integer(), nullable=True),
        sa.Column('went_over', sa.Boolean(), nullable=True),
        sa.Column('went_under', sa.Boolean(), nullable=True),
        sa.Column('game_commence_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movement_analysis', 'line_movements', ['movement_pct', 'hours_before_kickoff'], unique=False)
    op.create_index('idx_movement_lookup', 'line_movements', ['event_id', 'player_name', 'prop_type'], unique=False)
    op.create_index(op.f('ix_line_movements_event_id'), 'line_movements', ['event_id'], unique=False)
    op.create_index(op.f('ix_line_movements_player_name'), 'line_movements', ['player_name'], unique=False)

    # Create analysis_results table
    op.create_table(
        'analysis_results',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('analysis_name', sa.String(length=200), nullable=False),
        sa.Column('prop_type', sa.Enum('RUSHING_YARDS', 'RECEIVING_YARDS', name='proptype'), nullable=True),
        sa.Column('movement_threshold_pct', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('movement_threshold_abs', sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column('hours_before_threshold', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('sample_size', sa.Integer(), nullable=False),
        sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=False),
        sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=False),
        sa.Column('over_count', sa.Integer(), nullable=False),
        sa.Column('under_count', sa.Integer(), nullable=False),
        sa.Column('push_count', sa.Integer(), nullable=False),
        sa.Column('over_rate', sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column('under_rate', sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column('chi_square_statistic', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('p_value', sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column('is_significant', sa.Boolean(), nullable=True),
        sa.Column('confidence_interval_low', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('confidence_interval_high', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('baseline_over_rate', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('baseline_sample_size', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_name', 'analysis_results', ['analysis_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_analysis_name', table_name='analysis_results')
    op.drop_table('analysis_results')
    
    op.drop_index(op.f('ix_line_movements_player_name'), table_name='line_movements')
    op.drop_index(op.f('ix_line_movements_event_id'), table_name='line_movements')
    op.drop_index('idx_movement_lookup', table_name='line_movements')
    op.drop_index('idx_movement_analysis', table_name='line_movements')
    op.drop_table('line_movements')
    
    op.drop_index(op.f('ix_player_game_stats_player_name'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_event_id'), table_name='player_game_stats')
    op.drop_index('idx_player_stats_lookup', table_name='player_game_stats')
    op.drop_index('idx_player_stats_event', table_name='player_game_stats')
    op.drop_table('player_game_stats')
    
    op.drop_index(op.f('ix_prop_line_snapshots_player_name'), table_name='prop_line_snapshots')
    op.drop_index(op.f('ix_prop_line_snapshots_event_id'), table_name='prop_line_snapshots')
    op.drop_index('idx_prop_snapshot_time', table_name='prop_line_snapshots')
    op.drop_index('idx_prop_snapshot_lookup', table_name='prop_line_snapshots')
    op.drop_index('idx_prop_game_time', table_name='prop_line_snapshots')
    op.drop_table('prop_line_snapshots')
    
    op.execute('DROP TYPE IF EXISTS datasource')
    op.execute('DROP TYPE IF EXISTS proptype')
    # ### end Alembic commands ###

